### ISSUE TITLE
Crash on Android Release app

### ISSUE THREAD

**Issue by hardikpatelks** [idenfy/ReactNativeSDK#11]
App is working file while debug mode but crashing while starting sdk in the release build

I have atteched logs which I got when app is crashing.

 FATAL EXCEPTION: main
                                                                                                    Process: com.lokbest.stage, PID: 8549
                                                                                                    java.lang.RuntimeException: Unable to resume activity {com.my.app/com.idenfy.idenfySdk.core.presentation.view.IdenfyMainActivity}: java.lang.IllegalArgumentException: Unable to create call adapter for class Ce.j
                                                                                                        for method APIService.getPartnerInfo
                                                                                                    	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4961)
                                                                                                    	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4994)
                                                                                                    	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8176)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Unable to create call adapter for class Ce.j
                                                                                                        for method APIService.getPartnerInfo
                                                                                                    	at Ji.y.n(Unknown Source:46)
                                                                                                    	at Ji.k.d(Unknown Source:12)
                                                                                                    	at Ji.k.f(Unknown Source:67)
                                                                                                    	at Ji.v.b(Unknown Source:18)
                                                                                                    	at Ji.u.c(Unknown Source:24)
                                                                                                    	at Ji.u$a.invoke(Unknown Source:37)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy11.getPartnerInfo(Unknown Source)
                                                                                                    	at Ui.g.a(Unknown Source:35)
                                                                                                    	at Ui.m.d(Unknown Source:7)
                                                                                                    	at Od.c.k(Unknown Source:4)
                                                                                                    	at k1.a.n1(Unknown Source:56)
                                                                                                    	at androidx.fragment.app.i.M1(Unknown Source:14)
                                                                                                    	at androidx.fragment.app.v.f(Unknown Source:313)
                                                                                                    	at androidx.fragment.app.v.m(Unknown Source:127)
                                                                                                    	at androidx.fragment.app.q.b0(Unknown Source:346)
                                                                                                    	at androidx.fragment.app.q.i1(Unknown Source:81)
                                                                                                    	at androidx.fragment.app.q.Y(Unknown Source:21)
                                                                                                    	at androidx.fragment.app.l.k(Unknown Source:5)
                                                                                                    	at androidx.fragment.app.j.onResume(Unknown Source:13)
                                                                                                    	at com.idenfy.idenfySdk.core.presentation.view.IdenfyMainActivity.onResume(Unknown Source:0)
                                                                                                    	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
                                                                                                    	at android.app.Activity.performResume(Activity.java:8743)
                                                                                                    	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4951)
                                                                                                    	... 13 more
                                                                                                    Caused by: java.lang.IllegalStateException: Single return type must be parameterized as Single<Foo> or Single<? extends Foo>
                                                                                                    	at Ki.h.a(Unknown Source:118)
                                                                                                    	at Ji.u.d(Unknown Source:35)
                                                                                                    	at Ji.u.a(Unknown Source:1)
                                                                                                    	at Ji.k.d(Unknown Source:0)
                                                                                                    	... 35 more

**Comment by viktasidenfy** [comment]
Hello, please make sure have our Proguard rules added to your app - https://github.com/idenfy/iDenfyResources/blob/main/sdk/android/Proguard/proguard-rules.pro.
As well as `android.enableR8.fullMode=false` set in `gradle.properties`.

**Comment by hardikpatelks** [comment]
> Hello, please make sure you have our Proguard rules added to your app - https://github.com/idenfy/iDenfyResources/blob/main/sdk/android/Proguard/proguard-rules.pro. As well as `android.enableR8.fullMode=false` set in `gradle.properties`.

This help me to resolve my problem Thank you.
